services:
  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data/:/chroma/chroma/
      - ./vector_data/:/chroma/vector_data/
    command: chroma run --host 0.0.0.0 --port 8000
